spring:
  application:
    name: s3-viewer

s3-viewer:
  providers:
    - id: localstack
      name: LocalStack
      endpoint: http://localhost:4566
      region: us-east-1
      access-key: test
      secret-key: test
      path-style-access: true
      buckets:
        - demo-assets
        - demo-archive
logging:
  level:
    "software.amazon": "TRACE"
    "org.apache.hc.client5": "TRACE"