spring:
  application:
    name: s3-viewer
#  webflux:
#    base-path: /dev/service

s3-viewer:
  read-only-access: false
  providers:
    - id: localstack
      name: LocalStack
      endpoint: ${LOCALSTACK_ENDPOINT:http://localhost:4443}
      region: us-east-1
      access-key: test
      secret-key: test
      path-style-access: true
      all-buckets: true
#      buckets:
#        - demo-assets
#        - demo-archive
#        - spark-sql-prep-s3
    - id: rustfs
      name: rustfs
      endpoint: https://s3.cn-guangzhou-a.k8s.openprojectx.org
      region: us-east-1
      access-key: ${RUSTFS_ACCESS_KEY:test}
      secret-key: ${RUSTFS_SECRET_KEY:test}
      path-style-access: true
      buckets:
        - data
#  ui:
#    api-base-path: /dev/service/s3-viewer/api

logging:
  level:
    "software.amazon": "TRACE"
    "org.apache.hc.client5": "TRACE"
