spring:
  application:
    name: s3-viewer

s3-viewer:
  providers:
    - id: localstack
      name: LocalStack
      endpoint: ${LOCALSTACK_ENDPOINT:http://localhost:4566}
      region: us-east-1
      access-key: test
      secret-key: test
      path-style-access: true
      buckets:
        - demo-assets
        - demo-archive
    - id: rustfs
      name: rustfs
      endpoint: https://s3.cn-guangzhou-a.k8s.openprojectx.org
      region: us-east-1
      access-key: ${RUSTFS_ACCESS_KEY:test}
      secret-key: ${RUSTFS_SECRET_KEY:test}
      path-style-access: true
      buckets:
        - data

logging:
  level:
    "software.amazon": "TRACE"
    "org.apache.hc.client5": "TRACE"